config/routes.rb
Rails.application.routes.draw do
    get 'sessions/new'

    root 'site#index'

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    get '/sign_up', to: 'site#sign_up'
    post '/meetings/join', to: 'meetings#join'

    resources :users
    resources :meetings

    # Websockets
    mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  after_create_commit :create_upload_folder
  validates_presence_of :password
  validates_presence_of :code
  validates_presence_of :user

  belongs_to :user

  has_many :meeting_contents
  has_many :meeting_users

  def authenticate?(str)
    str == self.password
  end

  def create_upload_folder
    # Create /uploads folder if it doesn't exist
    dirname = "#{Rails.root}/uploads"
    FileUtils.mkdir_p(dirname) unless File.directory?(dirname)

    # Create folder to store images if it doesn't exist
    dirname = "#{dirname}/#{self.id}"
    FileUtils.mkdir_p(dirname) unless File.directory?(dirname)
  end
end

app/models/meeting_content.rb
class MeetingContent < ActiveRecord::Base
	validates_presence_of :meeting_id
	validates_presence_of :image

	belongs_to :meeting
end

app/models/meeting_user.rb
class MeetingUser < ActiveRecord::Base
    validates_presence_of :user_id
    validates_presence_of :meeting_id
    validates_presence_of :user_role

    validates :user_role, inclusion: { in: %w(presenter audience), message: "%(value) is not a valid role" }

    belongs_to :user
    belongs_to :meeting
    after_create_commit :create_image_folder

	# Only creates a folder for a presenter
    def create_image_folder
		return unless self.user_role == "presenter"
        dirname = "#{Rails.root}/uploads/#{self.meeting_id}/#{self.user_id}"
        FileUtils.mkdir_p(dirname) unless File.directory?(dirname)
        FileUtils.mkdir_p("#{dirname}/imgs") unless File.directory?("#{dirname}/imgs")
        # FileUtils.mkdir_p("#{dirname}/box") unless File.directory?("#{dirname}/box")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	validates_presence_of :email
	validates_presence_of :password

	validates :email, uniqueness: true

	has_many :meeting_users
    has_many :meetings

	def authenticate(pass)
		self.password == pass
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
    skip_before_filter :verify_authenticity_token
    before_action :set_meeting, only: [:show, :edit, :update, :destroy]
    before_action :check_user, only: [:show, :join]

    include MeetingsHelper

    def index
        flash[:notice] = params[:notice]
    end

    def join
        unless params[:code].present? || params[:password].present?
            redirect_to meeting_url
        end

        @meeting = Meeting.find_by(:code => params[:code])
        respond_to do |format|
            if @meeting && @meeting.authenticate?(params[:password])
                mu = MeetingUser.find_by(:user_id => current_user.id, :meeting_id => @meeting.id)
                if (mu.nil?)
                    mu = MeetingUser.new(:user_id => current_user.id, :meeting_id => @meeting.id, :user_role => params[:user_role])
                    mu.save
                end

                format.html { redirect_to @meeting, notice: "Meeting joined." }
            else
                format.html { redirect_to action: :index, notice: "Meeting not found." }
            end
        end
    end

    def show
        @mu = MeetingUser.find_by(:meeting_id => @meeting.id, :user_id => current_user.id)

        # TODO: Output error
        redirect_to meetings_url if @mu.nil?
    end

    # GET /meetings/new
    def new
    end

    # POST /meetings
    def create
        @meeting = Meeting.new :code => generate_code, :password => generate_password, :user_id => current_user.id

        respond_to do |format|
            if @meeting.save
                @mu = MeetingUser.new(:meeting_id => @meeting.id, :user_id => current_user.id, :user_role => params[:user_role])
                @mu.save!
                format.html { redirect_to @meeting, notice: 'Meeting created.' }
                format.json { render action: 'show', status: :created, location: @meeting }
            else
                format.html { render action: 'new' }
                format.json { render json: @meeting.errors, status: :unprocessable_entity }
            end
        end
    end

    # GET /meetings/1/edit
    def edit
    end

    # PATCH /meetings/1
    def update
    end

    private
    def set_meeting
        @meeting = Meeting.find(params[:id])
    end

    def meeting_params
        params.require(:user_role)
    end

    def check_user
        redirect_to "/" if current_user.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(:email => params[:sessions][:email].downcase)
		if user && user.authenticate(params[:sessions][:password])
			# Login
			log_in user
			redirect_to root_url 
		else
			# Output Error
			flash.now[:danger] = 'Invalid email/password combination'
			@msg = "Invalid Credentials"
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_to root_url
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  	def index
  	end

	def sign_up
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_filter :verify_authenticity_token
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    def index
        @users = User.all
    end

    # GET /users/1/
    def show
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
        @user = User.new(user_params)
        respond_to do |format|
            if @user.save
                log_in @user
                format.html { redirect_to root_url, notice: 'User was successfully created.' }
                format.json { render action: 'show', status: :created, location: @user }
            else
                format.html { redirect_to '/sign_up', notice: 'User exists.' }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
        respond_to do |format|
            if @user.update(user_params)
                log_in @user
                format.html { redirect_to root_url, notice: 'User was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: 'edit' }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
        @user.destroy
        respond_to do |format|
            format.html { redirect_to users_url }
            format.json { head :no_content }
        end
    end

    private
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.permit(:email, :password, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/magick_helper.rb
module MagickHelper
    # Convert image to black and white
    # @param image - Magick::Image or string with path to image
    # return Magick::Image in black and white
    def convert_to_black_and_white(image)
        return nil unless image.class == String || image.class == Image::Magick

        begin
            image = Magick::Image.read image if image.class == String
        rescue
            # path does not exist
        end

        # 2 indicates binary color, just black and white
        return image.quantize(2, Magick::GRAYColorspace, false)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
    def generate_code
        ('a'...'z').to_a.shuffle[0..7].join
    end

    def generate_password
        (0..9).to_a.shuffle[0..4].join
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in a user
	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>CaptureMyMeeting</title>
	<%= csrf_meta_tags %>
	<script type="text/javascript">
		window.meeting = {
			current_id: <%= current_user.present? ? current_user.id : -1%>,
			id: <%= @meeting.present? ? @meeting.id : 0 %>
		};
	</script>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag params[:controller] %>
</head>

<body>

	<div id="header">
		<a id="logo" class="noselect" href="/"><span><strong>CaptureMyMeeting</strong></span></a>
		<nav id="nav-head">
			<% if logged_in? %>
			<%= link_to current_user.email, edit_user_path(current_user) %>
			<%= link_to "Log out", logout_path, method: :delete %>
			<% else %>
			<a href="/login">Login</a>
			<% end %>
		</nav>
	</div>
	<%= yield %>

</body>
</html>

app/views/meetings/index.html.erb
<div class="container flex-center">
    <div class="card">
        <span class="title">Join</span>

        <div class="notice-default"><%= flash[:notice] %></div>

        <form method="POST" action="/meetings/join" class="form-control">
            <ul>
                <li><input name="user_role" type="radio" value="presenter"> Presenter</li>
                <li><input name="user_role" type="radio" value="audience" checked> Audience </li>
            </ul>

            <input type="text" name="code" placeholder="code" required>
            <input type="password" name="password" placeholder="password" required>
            <button class="submit"><i class="fa fa-sign-in" aria-hidden="true"></i><span>Join Meeting</span></button>
        </form>
    </div>
</div>

app/views/meetings/new.html.erb
<div class="container flex-center">
    <div class="card">
        <span class="title">Create</span>

        <form method="POST" action="/meetings" class="form-control new">
            <ul>
                <li><input name="user_role" type="radio" value="presenter" checked> I am a presenter</li>
                <li><input name="user_role" type="radio" value="audience"> I am an audience member </li>
            </ul>
            <button class="submit"><i class="fa fa-video-camera" aria-hidden="true"></i> <span>Start Meeting</span></button>
        </form>
    </div>
</div>

app/views/meetings/show.html.erb
<script type="text/javascript">
	window.meeting.role = "<%= @mu.user_role %>";
	window.meeting.id = "<%= @meeting.id %>";
</script>

<div id="info">
	<% redirect_to "/" if current_user.nil? %>

	<% if @mu.user_role == "presenter" %>
		<div class="actions hidden">
			<button class="set-box">Set Boundaries</button>
		</div>
	<% end %>
	<span>Code: <%= @meeting.code %></span>
	<span>Pass: <%= @meeting.password %></span>
	<span>Role: <%= @mu.user_role %></span>
</div>

<div id="meeting" class="container flex-center" data-meeting-id="<%= @meeting.id %>">
	<% if @mu.user_role == "presenter" %>
	<canvas class="hidden" id="meeting-canvas"></canvas>
	<video class="hidden" id="video-src" autoplay></video>
	<% end %>
	<img id="incoming" src="">
</div>

app/views/site/_home.html.erb
<div class="container flex-center">
    <%= link_to new_meeting_path, :class => "card card-trans" do %>
        <i class="fa fa-video-camera fa-6" aria-hidden="true"></i>
        <span>Start Meeting</span>
    <% end %>

    <%= link_to meetings_url, :class => "card card-trans" do %>
        <i class="fa fa-sign-in fa-6" aria-hidden="true"></i>
        <span>Join Meeting</span>
    <% end %>
</div>

app/views/site/index.html.erb
<% unless current_user %>
    <script>
        window.location.href = "<%= login_path %>";
    </script>
<% else %>
    <%= render 'home' %>
<% end %>

app/views/site/sign_up.html.erb
<div class="container flex-center">
    <div class="card">
        <span class="title">Sign Up</span>
        <form method="POST" action="/users" class="form-control">

        	<input name="email" type="text" placeholder="Email Address">
        	<input name="password" type="password" placeholder="********">

            <span class="alternate">Already have an account? <a href="/login">Login</a></span>
        	<button class="submit"><span>Sign Up</span></button>
        </form>
    </div>
</div>

app/views/users/show.html.erb
<h2>Hello <%= @user.email %></h2>